version: '3.1'

services:

  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: planmyday
      MYSQL_USER: mysql_usr
      MYSQL_PASSWORD: mysql_pwd

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - 8081:8080

volumes:
  mysql: