server:
  port: 3000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/planmyday
    username: mysql_usr
    password: mysql_pwd
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format-sql: true
      show-sql: true
  main:
    web-application-type: servlet
